import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import pluginVue from 'eslint-plugin-vue';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.output/**',
      '**/coverage/**',
      '**/build/**',
    ],
  },
  {
    files: ['**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
    plugins: { js },
    extends: ['js/recommended'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  tseslint.configs.recommended,
  pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },
  {
    files: ['**/*.{js,ts,vue}'],
    rules: {
      indent: [
        'error',
        2,
        {
          SwitchCase: 1,
          VariableDeclarator: 'first',
        },
      ],
      quotes: ['error', 'single'],
      'no-unsafe-optional-chaining': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'array-callback-return': 'error',
      'arrow-parens': 'error',
      'arrow-spacing': 'error',
      'block-scoped-var': 'error',
      'block-spacing': ['error', 'always'],
      'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
      camelcase: ['error', { properties: 'never' }],
      'comma-dangle': [
        'error',
        {
          arrays: 'always-multiline',
          objects: 'always-multiline',
          imports: 'always-multiline',
          exports: 'always-multiline',
          functions: 'ignore',
        },
      ],
      'comma-spacing': 'error',
      'comma-style': 'error',
      curly: 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': ['error', { allowKeywords: true }],
      'eol-last': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'func-call-spacing': 'error',
      'key-spacing': 'error',
      'new-cap': ['error', {
        capIsNew: false,
        newIsCap: true,
        properties: false,
      }],
      'no-array-constructor': 'error',
      'no-cond-assign': 'error',
      'no-confusing-arrow': ['error', { allowParens: true }],
      'no-console': 'warn',
      'no-const-assign': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-empty': 'error',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-extra-bind': 'error',
      'no-func-assign': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multi-spaces': 'error',
      'no-new': 'error',
      'no-new-wrappers': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'error',
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unused-expressions': 'error',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-var': 'warn',
      'no-whitespace-before-property': 'error',
      'object-shorthand': 'error',
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      'prefer-arrow-callback': 'warn',
      'prefer-spread': 'error',
      semi: ['error', 'always'],
      'space-infix-ops': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'space-before-blocks': 'error',
      'require-await': 'error',
      'no-duplicate-imports': 'error',
      'prefer-const': [
        'error',
        {
          destructuring: 'all',
          ignoreReadBeforeAssign: true,
        },
      ],
      'vue/require-explicit-emits': [
        'error',
        {
          allowProps: false,
        },
      ],
      'vue/multi-word-component-names': 'off',
      'vue/block-order': [
        'error',
        {
          order: ['template', 'style', 'script'],
        },
      ],
      'vue/require-default-prop': 'off',
    },
  },
]);
